export const data = {
  gallery: [
    {
      id: 1,
      imgGalleryAlt: "Gallery Img1",
      imgGalleryPath: "../assets/img/IMG-20241014-WA0028.jpg",
    },
    {
      id: 2,
      imgGalleryAlt: "Gallery Img2",
      imgGalleryPath: "../assets/img/gallery1.jpg",
    },

    {
      id: 4,
      imgGalleryAlt: "Gallery Img4",
      imgGalleryPath: "../assets/img/IMG-20241014-WA0023.jpg",
    },
    {
      id: 5,
      imgGalleryAlt: "Gallery Img5",
      imgGalleryPath: "../assets/img/pizza.jpg",
    },
  ],
  reviews: [
    {
      id: 1,
      title: "Sandwich de Milanesa",
      createdAt: "10 de Octubre 2024",
      imgAlt: "Imagen blog 1",
      imgReviewPath: "../assets/img/sanguche-de-milanesa.jpg",
      description: `Disfrutá de nuestro sándwich de milanesa, bien crujiente y acompañado de ingredientes frescos que le dan un toque único.`,
    },
    {
      id: 2,
      title: "Sopa Paraguaya",
      createdAt: "10 de Octubre 2024",
      imgAlt: "Imagen blog 2",
      imgReviewPath: "../assets/img/sopa-paraguaya.jpg",

      description: `Probá nuestra sopa paraguaya casera, hecha con los mejores ingredientes para garantizar ese sabor auténtico que tanto te gusta.`,
    },
    {
      id: 3,
      title: "Empanadas",
      createdAt: "10 de Octubre 2024",
      imgAlt: "Imagen blog 3",
      imgReviewPath: "../assets/img/empanadas.jpg",
      description: `Probá nuestras empanadas caseras recién horneadas o fritas, con una masa suave y rellenos generosos que explotan de sabor.`,
    },
  ],
  bestProducts: [
    {
      id: 1,
      title: "Alitas Fritas",
      price: "$6000 x 12 Piezas",
      link: "#",
      imgPath: "../assets/img/IMG-20241014-WA0029.jpg",
    },
    {
      id: 2,
      title: "Milanesas con Pure",
      price: "$3000",
      link: "#",
      imgPath: "../assets/img/IMG-20241014-WA0023.jpg",
    },
    {
      id: 3,
      title: "Arroz Woke",
      price: "$4000",
      link: "#",
      imgPath: "../assets/img/IMG-20241014-WA0030.jpg",
    },
    {
      id: 4,
      title: "Hamburguesa",
      price: "$5000 ",
      link: "#",
      imgPath: "../assets/img/IMG-20241014-WA0028.jpg",
    },
  ],
  specialProducts: [
    {
      id: 1,
      title: "Dumpling",
      price: "$500 x Unidad",
      link: "#",
      imgPath: "../assets/img/IMG-20241014-WA0027.jpg",
    },
    {
      id: 2,
      title: "Empanadas",
      price: "$1000 c/u.",
      link: "#",
      imgPath: "../assets/img/empanadas.jpg",
    },
    {
      id: 3,
      title: "Sopa Paraguaya",
      price: "$1000 Por Porcion",
      link: "#",
      imgPath: "../assets/img/sopa-paraguaya.jpg",
    },
    {
      id: 4,
      title: "Pizza",
      price: "$6000",
      link: "#",
      imgPath: "../assets/img/pizza.jpg",
    },
  ],
  allLunches: [
    {
      id: 1,
      title: "Sopa Paraguaya",
      price: "$1000 por Porciòn",
      link: "#",
      imgPath: "../assets/img/sopa-paraguaya.jpg",
    },
    {
      id: 2,
      title: "Milanesas con Pure",
      price: "$4000",
      link: "#",
      imgPath: "../assets/img/IMG-20241014-WA0023.jpg",
    },

    {
      id: 3,
      title: "Sandwich de Milanesa",
      price: "$3.000",
      link: "#",
      imgPath: "../assets/img/sanguche-de-milanesa.jpg",
    },
    {
      id: 4,
      title: "Empanadas",
      price: "$1000 C.U",
      link: "#",
      imgPath: "../assets/img/gallery1.jpg",
    },
    {
      id: 5,
      title: "Arroz Wok",
      price: "$3000",
      link: "#",
      imgPath: "../assets/img/IMG-20241014-WA0030.jpg",
    },
    {
      id: 6,
      title: "Hamburguesa",
      price: "$5000",
      link: "#",
      imgPath: "../assets/img/IMG-20241014-WA0028.jpg",
    },
    {
      id: 7,
      title: "Pizza",
      price: "$5500",
      link: "#",
      imgPath: "../assets/img/pizza.jpg",
    },
    {
      id: 8,
      title: "Alitas Fritas",
      price: "$6000 x 12 Piezas",
      link: "#",
      imgPath: "../assets/img/IMG-20241014-WA0029.jpg",
    },
    {
      id: 9,
      title: "Dumpling",
      price: "$500 x Pieza",
      link: "#",
      imgPath: "../assets/img/IMG-20241014-WA0027.jpg",
    },
  ],
  allDinners: [
    {
      id: 1,
      title: "Sopa Paraguaya",
      price: "$1000 por Porcion",
      link: "#",
      imgPath: "../assets/img/sopa-paraguaya.jpg",
    },
    {
      id: 2,
      title: "Milanesas con Pure",
      price: "$4000",
      link: "#",
      imgPath: "../assets/img/IMG-20241014-WA0023.jpg",
    },

    {
      id: 3,
      title: "Sandwich de Milanesa",
      price: "$3.000",
      link: "#",
      imgPath: "../assets/img/sanguche-de-milanesa.jpg",
    },
    {
      id: 4,
      title: "Empanadas",
      price: "$1000 C.U",
      link: "#",
      imgPath: "../assets/img/gallery1.jpg",
    },
    {
      id: 5,
      title: "Arroz Wok",
      price: "$3000",
      link: "#",
      imgPath: "../assets/img/IMG-20241014-WA0030.jpg",
    },
    {
      id: 6,
      title: "Hamburguesa",
      price: "$5000",
      link: "#",
      imgPath: "../assets/img/IMG-20241014-WA0028.jpg",
    },
    {
      id: 7,
      title: "Pizza",
      price: "$5500",
      link: "#",
      imgPath: "../assets/img/pizza.jpg",
    },
    {
      id: 8,
      title: "Alitas Fritas",
      price: "$6000 x 12 Piezas",
      link: "#",
      imgPath: "../assets/img/IMG-20241014-WA0029.jpg",
    },
    {
      id: 9,
      title: "Dumpling",
      price: "$500 x Pieza",
      link: "#",
      imgPath: "../assets/img/IMG-20241014-WA0027.jpg",
    },
  ],
};
